from django.urls import path, include
from .views import (
    IndexView,
    RegisterView,
    LogoutView,
    PublishIdeaView,
    PublishSurveyView,
    LikePostView,
    InspectIdeaView,
    SendCommentView,
    LikeCommentView,
    DislikeCommentView,
    FavouriteIdeasView,
    IdeasOverview,
    EditIdeaView,
    LeaderboardView,
    OpenSurveysView,
    VoteOpenSurveyView,
    StatusView,
    StatisticsView,
    ShopView,
    LandingView,
    AuthenticationView,
    ProfileView,
    FollowProfileView,
    AboutUsView,
    UpdatesView,
    DashBoardView,
    ViewNotificationView,
    ForgotPasswordView,
    ChangeThemeView,
    RateTopicView,
    DailyResetView,
    ContactUsView,
    SurveyView,
    TopicSuggestionsView,
    SuggestTopicView,
    LikeSuggestionView,
    BlogPartyView
)
from django.contrib.sitemaps.views import sitemap
from .sitemaps import StaticViewSiteMap , ProfileSiteMap, IdeaSiteMap

sitemaps = {
    'static': StaticViewSiteMap,
    'profiles': ProfileSiteMap,
    'ideas': IdeaSiteMap
}

urlpatterns = [
    path("", IndexView, name="index-page"),
    path("home", LandingView, name="home"),
    path("dashboard", DashBoardView, name="dashboard-page"),
    path("about-us", AboutUsView, name = "about-us-page"),
    path('contact-us', ContactUsView, name = 'contact-us-page'),
    path("login", AuthenticationView, name = "authentication"),
    path("register", RegisterView, name="register-page"),
    path('forgot-password', ForgotPasswordView, name = 'forgot-password-page'),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('robots.txt', include('robots.urls')),
    path('shuffle-ideas', IdeasOverview, name = 'random-ideas-page'),
    path('status', StatusView),
    path('stats', StatisticsView),
    path('shop', ShopView, name = 'shop-page'),
    path('change-theme', ChangeThemeView, name = 'change-theme-page'),
    path('updates', UpdatesView),
    path('ideas', FavouriteIdeasView, name = 'ideas-page'),
    path('topic-suggestions', TopicSuggestionsView, name = 'topic-suggestions-page'),
    path('suggest-topic', SuggestTopicView, name = 'topic-suggest-page'),
    path('leaderboard', LeaderboardView, name = 'leaderboard-page'),
    path('open-surveys', OpenSurveysView, name = 'open-surveys-page'),
    path('vote-open-survey/<int:survey_id>/<str:option_id>', VoteOpenSurveyView, name = 'vote-open-survey-page'),
    path("logout", LogoutView, name="logout-page"),
    path('edit-idea/<int:idea_id>', EditIdeaView, name = 'edit-idea-page'),
    path("publish-idea", PublishIdeaView, name="publish-idea-page"),
    path("publish-survey", PublishSurveyView, name = 'publish-survey-page'),
    path("like-idea/<int:post_id>", LikePostView, name="like-post-page"),
    path("like-suggestion/<int:suggestion_id>", LikeSuggestionView, name="like-suggestion-page"),
    path("inspect-idea/<int:idea_id>", InspectIdeaView, name="inspect-idea-page"),
    path("inspect-idea/<int:idea_id>/<str:sorting_method>", InspectIdeaView, name="inspect-idea-page-sorted"),
    path("send-comment/<int:idea_id>", SendCommentView, name = 'send-comment-page'),
    path('like-comment/<int:idea_id>/<int:comment_id>', LikeCommentView, name = 'like-comment-page'),
    path('dislike-comment/<int:idea_id>/<int:comment_id>', DislikeCommentView, name = 'dislike-comment-page'),
    path('profile/<str:username>', ProfileView, name = 'profile-page'),
    path('follow-profile/<int:profile_id>', FollowProfileView, name = 'follow-profile'),
    path('view-notification/<str:notification_key>', ViewNotificationView, name = 'view-notification-page'),
    path('rate-topic', RateTopicView, name = 'rate-topic-page'),
    path('daily-reset/<str:token>', DailyResetView),
    path('anket', SurveyView),
    path('blog', BlogPartyView, name = 'blog-page'),
]
